In [1]:
print('hello world')

hello world


In [2]:
import tensorflow as tf

In [5]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.utils import shuffle
from sklearn. preprocessing import scale

print ("Tensorflow版本是：", tf.version)

Tensorflow版本是： <module 'tensorflow._api.v2.version' from '/opt/anaconda3/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [6]:
print ("Tensorflow版本是：", tf.__version__)

Tensorflow版本是： 2.2.0


In [7]:
df = pd.read_csv('data/boston.csv', header = 0)

In [8]:
print(df.describe())

             CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     1.269195   13.295257    9.205158    0.140765    1.101175   15.679800   
std      2.399207   23.048697    7.169630    0.312765    1.646991   27.220206   
min      0.000000    0.000000    0.000000    0.000000    0.385000    3.561000   
25%      0.049442    0.000000    3.440000    0.000000    0.449000    5.961500   
50%      0.144655    0.000000    6.960000    0.000000    0.538000    6.322500   
75%      0.819622   18.100000   18.100000    0.000000    0.647000    6.949000   
max      9.966540  100.000000   27.740000    1.000000    7.313000  100.000000   

              AGE         DIS         RAD         TAX     PIRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    58.744660    6.173308   78.063241  339.317787   42.614980  332.791107   
std     33.104049    6.4764

In [10]:
df.head(3)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242.0   

   PIRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7

In [11]:
ds = df.values

In [12]:
print(ds)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]


In [13]:
x_data = ds[:,:12]

In [14]:
y_data = ds[:, 12]

In [15]:
print('x: ', x_data)
print('y: ', y_data)

x:  [[6.3200e-03 1.8000e+01 2.3100e+00 ... 2.9600e+02 1.5300e+01 3.9690e+02]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 2.4200e+02 1.7800e+01 3.9690e+02]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 2.4200e+02 1.7800e+01 3.9283e+02]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.7300e+02 2.1000e+01 3.9690e+02]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.7300e+02 2.1000e+01 3.9345e+02]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.7300e+02 2.1000e+01 3.9690e+02]]
y:  [ 4.98  9.14  4.03  2.94  5.33  5.21 12.43 19.15 29.93 17.1  20.45 13.27
 15.71  8.26 10.26  8.47  6.58 14.67 11.69 11.28 21.02 13.83 18.72 19.88
 16.3  16.51 14.81 17.28 12.8  11.98 22.6  13.04 27.71 18.35 20.34  9.68
 11.41  8.77 10.13  4.32  1.98  4.84  5.81  7.44  9.55 10.21 14.15 18.8
 30.81 16.2  13.45  9.43  5.28  8.43 14.8   4.81  5.77  3.95  6.86  9.22
 13.15 14.44  6.73  9.5   8.05  4.67 10.24  8.1  13.09  8.79  6.72  9.88
  5.52  7.54  6.78  8.94 11.97 10.27 12.34  9.1   5.29  7.22  6.72  7.51
  9.62  6.53 12.86  8.44  5.5   5.7   

In [21]:
train_num = 300
valid_num = 100
test_num = len(x_data) - train_num - valid_num

# 训练集
x_train = x_data[:train_num]
y_train = y_data[:train_num]

# 验证集
x_valid = x_data[train_num : train_num + valid_num]
y_valid = y_data[train_num : train_num + valid_num]

# 测试集
x_test = x_data[train_num + valid_num: train_num + valid_num + valid_num]
y_test = y_data[train_num + valid_num: train_num + valid_num + valid_num]

In [23]:
x_train = tf.cast(x_train, dtype = tf.float32)
x_valid = tf.cast(x_valid, dtype = tf.float32)
x_test = tf.cast(x_test, dtype = tf.float32)

In [24]:
def model(x, w, b):
    return tf.matmul(x, w) + b

In [25]:
W = tf.Variable(tf.random.normal([12, 1], mean = 0.0, stddev = 1.0, dtype = tf.float32))

In [26]:
B = tf.Variable(tf.zeros(1), dtype = tf.float32)

In [27]:
print(W, B)

<tf.Variable 'Variable:0' shape=(12, 1) dtype=float32, numpy=
array([[ 1.3375223 ],
       [ 0.4831867 ],
       [ 0.60867465],
       [ 0.2158689 ],
       [-0.25666663],
       [ 0.25764212],
       [ 0.7990075 ],
       [-0.16600476],
       [-0.17547683],
       [-0.2484233 ],
       [-1.4685133 ],
       [-0.09413887]], dtype=float32)> <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>
